version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip install zappa
      - zappa --version
      - zappa-config.py
      - cat zappa_settings.py
