version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - virtualenv venv
      - . ./venv/bin/activate
      - pip install zappa Django==2.1.7
  build:
    commands:
      - ./zappa-config.py
      - zappa status dev && zappa update dev || zappa deploy dev
