version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - virtualenv venv
      - . ./venv/bin/activate
      - pip install zappa
      - zappa --version
      - ls -la
      - ./zappa-config.py
      - cat ./zappa_settings.json
      - zappa undeploy dev
